// <auto-generated />
namespace BeatTheClock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tes333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tes333));
        
        string IMigrationMetadata.Id
        {
            get { return "201602290832473_tes333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
